apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cart-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Supanut1911/nonprod-k8s-config.git
    targetRevision: HEAD
    path: dev/pedjeab/cart
  destination:
    server: https://kubernetes.default.svc
    namespace: pg